package com.outpost.box;

public enum Status {

    PREPARED,
    PLACED_IN_SENDER_PARCEL_LOCKER,
    JOURNEY_TO_CENTRAL,
    CENTRAL,
    JOURNEY_TO_RECIPIENT_PARCEL_LOCKER,
    PLACED_IN_RECIPIENT_PARCEL_LOCKER,
    DELIVERED;
}
